version: '3.8'
services:
  anime_schedule_bot:
    build: .
    command: ["./build/app"]
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

volumes:
  pgdata:
